name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v3
    
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - 
        name: Push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: Deinococci/mastodon:latest
